# This is a basic workflow that is manually triggered
name: Build OpenBSD Qcow2

# Runs the action when it is triggered manually
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'OpenBSD release'
        default: '7.5'
        required: true
        type: string

jobs:
    build:
        uses: hcartiaux/openbsd-cloud-image/.github/workflows/build.yml@main
        with:
            filename: openbsd.qcow2
            release: ${{inputs.release}}

    test:
        needs: build
        uses: hcartiaux/openbsd-cloud-image/.github/workflows/test.yml@main
        with:
            filename: openbsd.qcow2

    release:
        needs: test
        runs-on: ubuntu-latest
        permissions: write-all
        environment:
          name: release
        steps:
        - name: Check out the repository to the runner
          uses: actions/checkout@v4
        - name: Generate tag name
          run: echo "tag=v${{ github.event.inputs.release }}_$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_ENV"
        - uses: actions/download-artifact@v4
          with:
            name: openbsd.qcow2
            path: images
        - uses: actions/download-artifact@v4
          with:
            name: openbsd.qcow2.sha256
            path: images
        - name: Verify the checksum
          run: |
            sha256sum -c images/openbsd.qcow2.sha256
        - name: Create a new release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh release create "${tag}" \
                --repo="$GITHUB_REPOSITORY" \
                --title="OpenBSD Cloud Image ${tag}" \
                --generate-notes
        - name: Upload the Qcow2 image and checksum file
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh release upload "${tag}" images/openbsd.qcow2
            gh release upload "${tag}" images/openbsd.qcow2.sha256
